version: '3.8'

services:
  rabbitmq:
    hostname: 'dev-rabbitmq'
    image: rabbitmq:3.13-rc
    ports:
      - 15671:15672
      - 5671:5672
    container_name: rabbit-mq
    environment:
      - RABBITMQ_DEFAULT_USER=renas
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/:z
    networks:
      - broker
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elastic
    volumes:
      - data01:/usr/share/elasticsearch/data:z
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - broker

volumes:
  data01:
    driver: local

networks:
  broker:
    driver: bridge